name: Build and deploy Node.js app to Azure Web App - listverseapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build (if any)
        run: |
          cd server
          npm install
          npm run build --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C38A35C1D2B4C55ABF6550A1B7126A6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B38A61CA45E4922BA86BD826D9C17BF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3999E9988F1E4BB0BEE4A0939F6BF969 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'listverseapp'
          slot-name: 'Production'
          package: ./server
